---
title: "Urban Fraction Analysis"
author: "Matthew Gordon"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
rootdir <- dirname(getwd())
library(tidyverse)
library(sf)
library(terra)
library(exactextractr)
library(rasterVis)
```

### Load packages and data

```{r, messages=FALSE, echo=FALSE, warnings=FALSE}
df.districts <- data.frame("district_name" = c("Gorkha", "Dhading", "Rasuwa", "Nuwakot", "Sindhupalchok", "Dolakha", "Ramechhap",
                                               "Kathmandu", "Bhaktapur", "Lalitpur", "Kabhrepalanchok", "Okhaldhunga", "Sindhuli", "Makwanpur",
                                               "Lamjung", "Tanahun", "Chitwan", "Solukhumbu", "Khotang", 
                                               "Kaski", "Parbat", "Syangja", "Palpa", "Gulmi", "Baglung",
                                               "Myagdi", "Arghakhanchi", "Nawalparasi", "Bhojpur", "Dhankuta", "Sankhuwasabha"),
                           "district" = c(36, 30, 29, 28, 23, 22, 21, 27, 26, 25, 24, 12, 20, 31, 37, 38, 35, 11, 13,
                                          40, 44, 39, 47, 46, 45, 43, 51, 48, 10, 7, 9), 
                           "dist_14" = c(rep(1, times = 14), rep(0, times = 17)),
                           "designation" = c(rep("severe", 7), rep("kathmandu", 3), rep("crisis", 4), rep("heavy", 5), rep("hit", 6), rep("slight", 6)))

df.shp <- st_read(paste(rootdir, "/data/shapefiles/NPL_adm", sep = ""), "NPL_adm3") %>%
              mutate(district_name = if_else(NAME_3=="Chitawan", "Chitwan",
                                                 if_else(NAME_3=="Tanahu", "Tanahun",
                                                         if_else(NAME_3=="Kavrepalanchok","Kabhrepalanchok",as.character(NAME_3)))))

df.shp <- merge(df.shp, df.districts, by = "district_name", all = TRUE) %>%
            mutate(dist_14 = if_else(is.na(dist_14),0,dist_14),
                 designation = if_else(is.na(designation),"none",as.character(designation)))

severe <- st_union(filter(df.shp, designation == "severe"))
crisis <- st_union(filter(df.shp, designation == "crisis"))
heavy_losses <- st_union(filter(df.shp, designation == "heavy"))
moderate <- st_union(filter(df.shp, designation == "hit"))
slight <- st_union(filter(df.shp, designation == "slight"))
none <- st_union(filter(df.shp, designation == "none"))
kathmandu <- st_union(filter(df.shp, designation == "kathmandu"))
df.designations <- st_sf(designation = factor(c("severe", "crisis", "heavy losses", "moderate", "slight", "none", "kathmandu"), 
                                              levels = c("severe", "crisis", "heavy losses", "moderate", "slight", "none", "kathmandu")), 
                         geometry = c(severe, crisis, heavy_losses, moderate, slight, none, kathmandu))
rm(heavy_losses, moderate, none, severe, slight, crisis, df.shp)

ggplot(df.designations) + geom_sf(aes(fill = designation))
```

```{r}
setwd(paste(dirname(dirname(getwd())), "/Nepal/urbanfraction/kernel", sep = ""))

pixel1412 <- rast("change1412_de95_1km.tif")
pixel1413 <- rast("change1413_de95_1km.tif")
pixel1614 <- rast("change1614_de95_1km.tif")
pixel1714 <- rast("change1714_de95_1km.tif")
#pixel1814 <- rast("change1814_Nepalc.tif")
#pixel1914 <- rast("change1914_Nepalc.tif")

df.designations <- st_transform(df.designations, crs(pixel1412))
```

```{r}
ext12 = exact_extract(pixel1412, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & value!=0])
rm(pixel1412)
ext13 = exact_extract(pixel1413, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & value!=0])
rm(pixel1413)
ext16 = exact_extract(pixel1614, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & value!=0])
rm(pixel1614)
ext17 = exact_extract(pixel1714, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & value!=0])
rm(pixel1714)
#ext18 = exact_extract(pixel1814, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & value!=0])
#rm(pixel1814)
#ext19 = exact_extract(pixel1914, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & value!=0])
#rm(pixel1914)
```

```{r}
df.q <- data.frame("chg" = c(quantile(ext12[[1]], seq(.01,.99,.01)),
                              quantile(ext13[[1]], seq(.01,.99,.01)),
                              quantile(ext16[[1]], seq(.01,.99,.01)),
                              quantile(ext17[[1]], seq(.01,.99,.01)),
                             quantile(ext12[[2]], seq(.01,.99,.01)),
                              quantile(ext13[[2]], seq(.01,.99,.01)),
                              quantile(ext16[[2]], seq(.01,.99,.01)),
                              quantile(ext17[[2]], seq(.01,.99,.01)),
                             quantile(ext12[[3]], seq(.01,.99,.01)),
                              quantile(ext13[[3]], seq(.01,.99,.01)),
                              quantile(ext16[[3]], seq(.01,.99,.01)),
                              quantile(ext17[[3]], seq(.01,.99,.01)),
                             quantile(ext12[[4]], seq(.01,.99,.01)),
                              quantile(ext13[[4]], seq(.01,.99,.01)),
                              quantile(ext16[[4]], seq(.01,.99,.01)),
                              quantile(ext17[[4]], seq(.01,.99,.01)),
                             quantile(ext12[[5]], seq(.01,.99,.01)),
                              quantile(ext13[[5]], seq(.01,.99,.01)),
                              quantile(ext16[[5]], seq(.01,.99,.01)),
                              quantile(ext17[[5]], seq(.01,.99,.01)),
                             quantile(ext12[[6]], seq(.01,.99,.01)),
                              quantile(ext13[[6]], seq(.01,.99,.01)),
                              quantile(ext16[[6]], seq(.01,.99,.01)),
                              quantile(ext17[[6]], seq(.01,.99,.01)),
                             quantile(ext12[[7]], seq(.01,.99,.01)),
                              quantile(ext13[[7]], seq(.01,.99,.01)),
                              quantile(ext16[[7]], seq(.01,.99,.01)),
                              quantile(ext17[[7]], seq(.01,.99,.01))),
                   "qtile" = rep(seq(.01,.99,.01),28),
                   "year" = rep(c(rep(2012, 99), rep(2013, 99), rep(2016, 99), rep(2017,99)), 7),
                   "designation" = c(rep("severe", 396), rep("crisis", 396), rep("heavy", 396), rep("moderate", 396), 
                                     rep("slight", 396), rep("none", 396), rep("kathmandu", 396)))

ggplot(df.q) + geom_point(aes(x = chg, y = year)) + 
  facet_wrap(~designation) + 
  theme(legend.position = "none") + theme_bw() 
```
```{r}
g1 = ggplot() + 
  geom_histogram(aes(x = ext13[[1]]), fill = "red", alpha = .5, bins = 100, position = "identity") + 
  geom_histogram(aes(x = ext17[[1]]), fill = "blue", alpha = .5, bins = 100, position = "identity") +
  labs(title = "severe") + xlim(0,200)

g2 = ggplot() + 
  geom_histogram(aes(x = ext13[[6]]), fill = "red", alpha = .5, bins = 100, position = "identity") + 
  geom_histogram(aes(x = ext17[[6]]), fill = "blue", alpha = .5, bins = 100, position = "identity") +
  labs(title = "none") + xlim(0,200)

cowplot::plot_grid(g1, g2)
```


```{r}
rm(ext12, ext13, ext16, ext17)
setwd(paste(dirname(dirname(getwd())), "/Nepal/urbanfraction/kernel", sep = ""))

pixel1412 <- rast("change1412_in95_1km.tif")
pixel1413 <- rast("change1413_in95_1km.tif")
pixel1614 <- rast("change1614_in95_1km.tif")
pixel1714 <- rast("change1714_in95_1km.tif")
#pixel1814 <- rast("change1814_Nepalc.tif")
#pixel1914 <- rast("change1914_Nepalc.tif")

df.designations <- st_transform(df.designations, crs(pixel1412))
```

```{r}
ext12 = exact_extract(pixel1412, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & abs(value)>5])
rm(pixel1412)
ext13 = exact_extract(pixel1413, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & abs(value)>5])
rm(pixel1413)
ext16 = exact_extract(pixel1614, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & abs(value)>5])
rm(pixel1614)
ext17 = exact_extract(pixel1714, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & abs(value)>5])
rm(pixel1714)
#ext18 = exact_extract(pixel1814, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & abs(value)>5])
#rm(pixel1814)
#ext19 = exact_extract(pixel1914, df.designations, function(value, coverage_fraction) value[coverage_fraction >= .5 & !is.na(value) & abs(value)>5])
#rm(pixel1914)
```

```{r}
df.q <- data.frame("chg" = c(quantile(ext12[[1]], seq(.01,.99,.01)),
                              quantile(ext13[[1]], seq(.01,.99,.01)),
                              quantile(ext16[[1]], seq(.01,.99,.01)),
                              quantile(ext17[[1]], seq(.01,.99,.01)),
                             quantile(ext12[[2]], seq(.01,.99,.01)),
                              quantile(ext13[[2]], seq(.01,.99,.01)),
                              quantile(ext16[[2]], seq(.01,.99,.01)),
                              quantile(ext17[[2]], seq(.01,.99,.01)),
                             quantile(ext12[[3]], seq(.01,.99,.01)),
                              quantile(ext13[[3]], seq(.01,.99,.01)),
                              quantile(ext16[[3]], seq(.01,.99,.01)),
                              quantile(ext17[[3]], seq(.01,.99,.01)),
                             quantile(ext12[[4]], seq(.01,.99,.01)),
                              quantile(ext13[[4]], seq(.01,.99,.01)),
                              quantile(ext16[[4]], seq(.01,.99,.01)),
                              quantile(ext17[[4]], seq(.01,.99,.01)),
                             quantile(ext12[[5]], seq(.01,.99,.01)),
                              quantile(ext13[[5]], seq(.01,.99,.01)),
                              quantile(ext16[[5]], seq(.01,.99,.01)),
                              quantile(ext17[[5]], seq(.01,.99,.01)),
                             quantile(ext12[[6]], seq(.01,.99,.01)),
                              quantile(ext13[[6]], seq(.01,.99,.01)),
                              quantile(ext16[[6]], seq(.01,.99,.01)),
                              quantile(ext17[[6]], seq(.01,.99,.01)),
                             quantile(ext12[[7]], seq(.01,.99,.01)),
                              quantile(ext13[[7]], seq(.01,.99,.01)),
                              quantile(ext16[[7]], seq(.01,.99,.01)),
                              quantile(ext17[[7]], seq(.01,.99,.01))),
                   "qtile" = rep(seq(.01,.99,.01),28),
                   "year" = rep(c(rep(2012, 99), rep(2013, 99), rep(2016, 99), rep(2017,99)), 7),
                   "designation" = c(rep("severe", 396), rep("crisis", 396), rep("heavy", 396), rep("moderate", 396), 
                                     rep("slight", 396), rep("none", 396), rep("kathmandu", 396)))

ggplot(df.q) + geom_point(aes(x = chg, y = year)) + 
  facet_wrap(~designation) + 
  theme(legend.position = "none") + theme_bw() 
```


```{r}
g1 = ggplot() + 
  geom_histogram(aes(x = ext13[[1]]), fill = "red", alpha = .5, bins = 100, position = "identity") + 
  geom_histogram(aes(x = ext17[[1]]), fill = "blue", alpha = .5, bins = 100, position = "identity") +
  labs(title = "severe") + xlim(0,200)

g2 = ggplot() + 
  geom_histogram(aes(x = ext13[[6]]), fill = "red", alpha = .5, bins = 100, position = "identity") + 
  geom_histogram(aes(x = ext17[[6]]), fill = "blue", alpha = .5, bins = 100, position = "identity") +
  labs(title = "none") + xlim(0,200)

cowplot::plot_grid(g1, g2)
```